### ISSUE TITLE
Auto update loop

### ISSUE THREAD

**Issue by igotquestions** [dasilva333/TowerGhostForDestiny#670]
I install tower ghost, open it, gives my update changes list, I close that...then gives me login choices...I choose xbox....then go to input my name.....window closes and tower ghost goes to just grey background....then loops process again

**Comment by binkley33w20** [comment]
Same for me.

**Comment by hendersj** [comment]
I am seeing this on Android as well, just started yesterday.  If I turn off auto update (which can be tricky), i don't get any inventory.  I tried wiping data/cache, but that didn't help.

**Comment by N1ceDrgn** [comment]
This issue started for me a couple of days ago. Today I tried clearing the cache and even reinstalling the app with no change.
After the reinstall, it continues to loop, "updating". A update will start, then back out, then start again. It's citing pretty strange. I did try letting it run for a while, in case what I installed was out of date but there was no change.
I know dasilva333 works hard on this and I really enjoy the app. When it doesn't work right, like now, I really notice how much I enjoy the app. I hope a fix comes soon.

**Comment by vrdarkone** [comment]
Same thing for me started yesterday out of the blue. Did all the steps mentioned above, cleared cache etc / Uninstalled and reinstalled same thing. Auto refresh appears to be off and still is stuck in this loop. This is my favorite app to move shit around and and I had to use vault helper or something instead.. :-(

**Comment by hendersj** [comment]
Starting yesterday, it seems this issue is resolved - working OK now on my Android tablet.

**Comment by binkley33w20** [comment]
It's doing the same thing again. Update loop!

**Comment by hendersj** [comment]
I noticed this yesterday again as well on my Android tablet.

**Comment by N1ceDrgn** [comment]
Yes, this problem has returned. I see it on my Android device but not in a Chrome browser.

**Comment by Grimsalt** [comment]
Continued from [closed] issue [#677](https://github.com/dasilva333/TowerGhostForDestiny/issues/677)

> @Grimsalt have you tried a full reinstall and clearing your app cache in android? feel free to follow issue #670 for more info on that

@dasilva333 Thank you for responding.  Clearing app cache + data & full reinstall didn't fix.  Found work-around *.  Used 3rd party file explorer to manually search and delete hidden residual file `tower_ghost.css` in location path `/storage/emulated/0/app/resources/` that remained after multiple deletion attempts from the device, the store, and 3rd party apps.  This didn't resolve the issue, but somehow un-froze the splash screen, buying enough time to open `Settings` and un-tick the auto-update option.  The app now works as before, with that function disabled.  

*: for Android 5.1.1 on Nexus 10

**Comment by dasilva333** [comment]
@Grimsalt thank you so much for that report, can you provide me what 3rd party file explorer you used? did it require root access to remove those files? I'm surprised an uninstall isn't removing those files. Can you let me know what version you're using right now after you unticked auto-update? Have you tried enabling it again to see if it works?

Let me know, thanks!

**Comment by Grimsalt** [comment]
@dasilva333  Sure, glad to help, I really love this app and value you're hard work :)

- I used [ES File Explorer File Manager](https://play.google.com/store/apps/details?id=com.estrongs.android.pop).  Did **not** require root access.  However, make sure left panel options "Show Hidden Files" is switched on.  

- Right now, I'm using Tower Ghost version 3.9.3.2 with the unticked auto-update.

- For your benefit, I enabled auto-updates again to see what happens.  Went straight back to the loop and blank screen issue again...  There might be another hidden file somewhere to purge, have to spend more time hunting it down manually I guess

**Comment by dasilva333** [comment]
Thanks I'll install that on my Android and play around with TGD and the file system to see what's going on there, this might be a problem related to cordova-app-loader.

**Comment by sdholden** [comment]
I've got this issues on two Samsung Galaxy tablets - one "kitkat" and one "lollipop" version of Android.  Turning off aut-updates let's me use 3.9.3.2 version ok.  Been going on for a month or so....

**Comment by hendersj** [comment]
Yeah, it's still a problem here - and with The Dawning having started, the app's now not usable for me on my Android tablet (also a Samsung Galaxy S 10.5, if that makes a difference).  Tried removing and reinstalling, but no joy..

**Comment by sdholden** [comment]
Haven't been able to use for months on my tablets.  Had to switch to Ishtar commander. Any news on a Fix?

**Comment by N1ceDrgn** [comment]
I haven't been able to use the app on my Android device or iPad for a long time now. I can only access the app via Chrome. I've had to resort to use Ishtar Academy ad well and still don't like it. I have been and still am waiting for this app to begin working again.

**Comment by hendersj** [comment]
@dasilva333 - is there any way in which those of us having this issue can help diagnose it?

**Comment by Stargrove** [comment]
@hendersj  @dasilva333 

I tried to download an older version from Amazon which is 3.8.x showing the same behavior, so I assume it is not version related
I have this issue on Nexus 5 and 10 (Android 5 and 6)

What a pity...

**Comment by DarkCDI** [comment]
i have the same issue on my galaxy s8+ with android 7.0
auto update loop, and if i switched off the auto update, not loading anything
