### ISSUE TITLE
Moving item when only item in that category

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#91]
Current behavior:
1. Weapon, armor, etc. to move is the only item in that category on character
2. Initiating a move from a Loadout selection fails with no discernable error or note. 
3. Move of the current item and all other items in the list is stalled and must be cancelled

Expected behavior:
1. Weapon, armor, etc. to move is the only item in that category on character
2. Move initiates the move of the lone item, and swaps with another applicable item (vault, other character?)
3. Move succeeds and notes that an item was moved from vault or character due to no other item in category with selected item

Suggestions:
1. Prompt user to cancel and move an item to the category for the lone item
2. Fail gracefully and notify user
3. Select a random category item from vault (Legendary for Legendary, Exotic for Exotic, etc) and populate category then move the requested item.

**Comment by dasilva333** [comment]
Hey man it seems it's simply crashing for you while transferring your loadouts, if you're running it on Chrome please try to provide some error debug logs by pressing F12, visit the Console tab, try to reproduce the error and copy and paste any messages you to www.pastebin.com and show them here.

Also it doesn't matter if it's one item or multiple items in your loadouts you'll always get a confirmation popup so the user is sure they are willing to commit to the changes presented.

Thanks

**Comment by rkingsla** [comment]
Hey, Richard…  

 

Good hearing from you again.  I’ll enable the debugging and see what it’s doing.  Now that you’ve confirmed that it should be working, I’ll test to those scenarios and provide you some feedback – positive or constructive – as soon as I can gather it.

 

Much appreciate it, and enjoy the $10.00 I sent the other day.  Frankly, I don’t come across many projects like yours that is so dedicated and so appreciated very often.  I like to invest in projects that have impact.  I will absolutely invest more in your time as I can afford.

 

Thank you for everything that you are doing.  It’s a simply awesome tool.

 

Rick

**Comment by dasilva333** [comment]
@rkingsla I'm going to need a follow up from you to know if this is still an issue or whether I should close it. Thanks

**Comment by rkingsla** [comment]
Sorry...  A bit distracted on other things.  I'll get a repro and note here if it's resolved or with logs from Dev Mode in Chrome.  Thank you!

**Comment by rkingsla** [comment]
XHR finished loading: POST "https://www.bungie.net/Platform/Destiny/EquipItem/".
12XHR finished loading: POST "https://www.bungie.net/Platform/Destiny/TransferItem/".
XHR finished loading: POST "https://www.bungie.net/Platform/Destiny/EquipItem/".
4XHR finished loading: POST "https://www.bungie.net/Platform/Destiny/TransferItem/".
XHR finished loading: POST "https://www.bungie.net/Platform/Destiny/EquipItem/".
8XHR finished loading: POST "https://www.bungie.net/Platform/Destiny/TransferItem/".
app.js:201 Uncaught TypeError: Cannot read property 'equip' of undefined
tryNextItem @ app.js:201
tryNextItem @ app.js:208
Item.unequip @ app.js:214
done @ app.js:369
Item.store @ app.js:424
transferNextItem @ loadouts.js:159
(anonymous function) @ loadouts.js:171
(anonymous function) @ app.js:346
r.onload @ bungie.js:99

![move-crota-items](https://cloud.githubusercontent.com/assets/2037051/7359723/6d73feea-ed07-11e4-9bdf-546961069482.png)

**Comment by dasilva333** [comment]
@rkingsla What version are you using? (i keep the version in the top left but you cropped it out of the image) Can you try 2.1.5 and let me know if it still persists? thanks

**Comment by rkingsla** [comment]
My bad, Richard.  I did unintentionally crop it out.  2.1.1.  I’ll try a repro with 2.15.

**Comment by dasilva333** [comment]
@rkingsla sorry man 2.1.5/2.1.6 were messed up really bad and I didn't catch it until just recently please try 2.1.7 instead. There was a few loadout issues fixed in between all these versions so hopefully that took care of it for you. Let me know thanks

**Comment by dasilva333** [comment]
@rkingsla please confirm if the issue is still apparent in 2.1.9 so I can go ahead and close this ticket. thanks!

**Comment by rkingsla** [comment]
Let me do this because I’m not sure that my issue is being well communicated…  I will pull some code from Chrome with where it fails, and pseudo-code for what I expect to happen.

 

I will TRY and get that done today, this evening.  I think I’m failing to convey the issue that I see….

**Comment by dasilva333** [comment]
@rkingsla no i totally understand the problem you even showed me the crash and the bug, simply try it on 2.1.9 or 2.1.7 and see if you can get it to still happen. No need to do anything fancy or instrument any code simply try to get it to fail and report back if it does crash and what line (ideally the logs)

Thanks

**Comment by rkingsla** [comment]
Professing to potentially being the most naïve Chrome dev ever (I don’t actively develop for Chrome…  :-/ ) can you point me to where I would turn on logging so that I can give you details in depth? I’ve found the logging for Chrome crashes, but not Chrome Extension App logging for specific details on errors in TGD…

 

The issue still repros in 2.1.9… Last item in a bucket will not transfer.

 

Rick

**Comment by dasilva333** [comment]
@rkingsla wow that's incredible it really seems I'm chasing an actual bug. I'm not sure what the condition is for the crash. To enable debug logging just do what you did last time where you provide a screenshot of the Console tab when the crash happened, that was really helpful in having me figure out the cause of the issue.

One more thing, do you have any idea as to why you think the last one would be problematic? Have you tried creating that same loadout again with the same items and tried to reproduce the issue? If you could that would be great thanks

**Comment by Titus-s** [comment]
Probably this is similar issue I've requested earlier. 
Using version 2.1.9 for chrome (2.2.2 doesn't work for me - load only vault)

Steps (simplified version):
1. Have only one item in bucket on source character (here - Light of the Abbys)
![screenshot_2015 05 01_00h44m26s_001_](https://cloud.githubusercontent.com/assets/11790750/7424029/c79701f0-ef9c-11e4-832d-36025e9bee3d.png)
2. Put it into loadout
![screenshot_2015 05 01_00h44m59s_002_](https://cloud.githubusercontent.com/assets/11790750/7424050/f0d38af2-ef9c-11e4-82bb-6fa83b3bc35a.png)
3. Try to move this loadout to another character (the orange one)
![screenshot_2015 05 01_00h45m26s_003_](https://cloud.githubusercontent.com/assets/11790750/7424061/0e4c689c-ef9d-11e4-8e2b-ab7ee9a5f338.png)

Actual result:
It stops on the beginning . Nothing happen, no error. You can only cancel transfer.
Below logs from console:
![screenshot_2015 05 01_00h47m12s_004_](https://cloud.githubusercontent.com/assets/11790750/7424112/cb2952f4-ef9d-11e4-9825-05740e105dec.png)

If this item was second or third in queue in loadout then progress bar stops in the middle. 
Please note that this is only one case when it stops. I can provide you another cases if you want.

**Comment by rkingsla** [comment]
I will provide some added feedback Titus, thanks for helping on this and confirming what we’re seeing.

 

Richard – I’m sure it on the bucket list, but being a professional writer (and REALLY not wanting to be THAT guy) PLEASE change the verbiage in the screen shot below:

 

Current: Light of the Abyss will be just be moved.

Suggest: Light of the Abyss will be moved.

 

Certainly there is likely overlapping logic here in relation to moving and equipping.

 

I know, we’re working a bug – not a grammar edit.  :)

**Comment by dasilva333** [comment]
Easy enough to change the verbiage no problem as for the actual bug I'll try to reproduce it using @Titus-s feedback tonight thanks guys

**Comment by dasilva333** [comment]
Try 2.2.7 and let me know how it goes thanks guys

**Comment by Titus-s** [comment]
The only change I've noticed is that now it display message "You cannot perform this action on an equipped item". Except this it behave like before: moving loadout stops.
Is it possible to change it to perform next action and at the end inform user that this item was not moved?

**Comment by dasilva333** [comment]
Try 2.2.8 I added some more logic for when there's only one item

**Comment by Titus-s** [comment]
Still doesn't work in most cases. 
I've check your changes - it works only when in target character bucket is 9 items. Otherwise it's not working. Behavior like before.

**Comment by dasilva333** [comment]
@Titus-s good looking out after testing it initially it seemed to be working fine, later on I'm using it and I realize it's horribly broken. Try 2.3.0 it has a few more fixes for loadouts. Thanks

**Comment by Titus-s** [comment]
It's working fine now. 
Only one suggestion - it should be visible on first sight that item will not be moved. Now it looks similar to case when item is already in destination bucket. Look at below screenshots:
![screenshot_2015 05 04_12h45m08s_006_](https://cloud.githubusercontent.com/assets/11790750/7452269/ce87ceba-f25b-11e4-9e5b-7116ede5ee61.png)
![screenshot_2015 05 04_12h45m35s_007_](https://cloud.githubusercontent.com/assets/11790750/7452270/d2dfd282-f25b-11e4-93c8-cd97599dc6e9.png)
Can you make it more visible when item will not be moved? 
For example:
- red X on white icon 

![screenshot_2015 05 04_12h45m08s_006__2](https://cloud.githubusercontent.com/assets/11790750/7452578/89cbf842-f25f-11e4-9a5e-5cfb82e3f8dc.png)
- red font

![screenshot_2015 05 04_12h45m08s_006__3](https://cloud.githubusercontent.com/assets/11790750/7452614/3d296ca8-f260-11e4-95f7-102f796a0e96.png)

**Comment by dasilva333** [comment]
@Titus-s check version 2.3.5 it has a big improvement of the current setup thanks

**Comment by Titus-s** [comment]
One more issue. 
Steps:
1. Create loadout
2., Select one Primary and one Special weapon 
3. Try to move loadout to character where primary bucket is full (contains 10 items)
Actual results:
Transfer Confirm dialog box says that primary weapon will be swap
When you click Transfer appear information "There are no item slots available to transfer this item" and loadout transfer stops. 
Expected results:
Transfer Confirm dialog shows that primary weapon will not be moved. 
After click Transfer it skips moving primary weapon and continue moving next items.

**Comment by dasilva333** [comment]
@Titus-s thanks for finding all these weird edge cases for me. I got it fixed now but not how you expected it. Even without the special weapon in the loadout simply transferring one item to a bucket that's full prompts that it can do it but then fails. I would expect for it to say that it can't do it and then skip it or say it can do it and then get it done, I went with the latter option.

So just to clarify when you try to apply a loadout to a bucket that's full it'll still prompt you to swap, and the swap will actually work now, I fixed it by changing the order how things are moved. Rather than moving the targetItem first then the swapItem I'm moving the swapItem first (to clear up some space) and then the targetItem into it (now that there's room available).

Thanks and expect the fix as part of 2.3.6

**Comment by Titus-s** [comment]
I found some strange issue on version 2.3.7. During test character was on Orbit.
Yesterday I found that sometimes I cannot move item equipped on source character. No error in console. 
Today I try to move loadout with armor, as I do everyday. It stoped in the middle.
Here is what I have before move loadout:
![screenshot_2015 05 07_19h43m56s_008_](https://cloud.githubusercontent.com/assets/11790750/7522001/91cfd87a-f4f2-11e4-96d9-4fae643115f7.png)
Then loadout:
![screenshot_2015 05 07_19h45m21s_009_](https://cloud.githubusercontent.com/assets/11790750/7522011/a3d85556-f4f2-11e4-9f8e-ca7f1eaef92a.png)
Here is results:
![screenshot_2015 05 07_19h46m11s_010_](https://cloud.githubusercontent.com/assets/11790750/7522019/b1d2adb4-f4f2-11e4-98ed-14a87846540d.png)
![screenshot_2015 05 07_19h46m23s_011_](https://cloud.githubusercontent.com/assets/11790750/7522026/bba678ca-f4f2-11e4-9e33-8f54960c0c54.png)
At the end I've try to move my boots equipped on "Yellow" character and move to the "Blue" character.
Nothing happen. I think that both cases are caused by the same function. 
That's all what I have now, I'll try to investigate this issue.

**Comment by dasilva333** [comment]
Thanks for the update @Titus-s I'll see if I can reproduce it

**Comment by Titus-s** [comment]
In version 2.4.1 it still doesn't work. 
I've try to debug it, and for now I know that function unequip in Item.js doesn't work as it should. 
In line 96 filter doesn't return any items, otherItems.length is 0, so it can't equip another item. 
Hope it help.

**Comment by dasilva333** [comment]
Ill be debugging this today hopefully get it all fixed. Thanks for the help

**Comment by dasilva333** [comment]
Sorry guys I still can't reproduce it. I don't know if it's because I have 3 different classes and it only happens with transferring and equipping armor across profiles.

**Comment by Titus-s** [comment]
Tested on version 2.4.2, 
There is only one error in console (appear during loading extension in chrome):
Navigated to chrome-extension://ejdpapdpfojhhfkkdecdjkbdmdmkekha/www/index.html
index.html:49 GET chrome-extension://ejdpapdpfojhhfkkdecdjkbdmdmkekha/www/cordova.js net::ERR_FILE_NOT_FOUND
I've made some investigation. Here is detail:
It turn out that all my armor (helmet, gauntlets and boot armor) have item.type = 0
(I've check also weapons and all types has different item.type from 6 to 14)
In Item.js in line 97 is condition: 
item.type > 0 && ...
when I've remove this, it start to work.

I've check older version which work for me - there was no condition about item.type but I've found that also there all armors have item.type = 0.
It must help you :)

**Comment by dasilva333** [comment]
Thanks a ton man I've no clue why I added that in there I really appreciate helpful people like you taking the time to understand and really help out. Expect the fix in 2.4.5

**Comment by rkingsla** [comment]
Sorry, folks.... Haven't been reporting on this issue.  Might have gotten a nice shout out (LOL!) if I'd have stayed with this more.

Scenario I noticed today:

Vault has 36 weapon items in it. Due to the way that items move, if I try and move and item from Character A to Character B, it's going to fail with the somewhat vague message "There are no item slots available to transfer this item." Available slot on the destination character?  If *I* didn't know that the process is:

*Determine item to move.
*Move item from Character A to vault
*Move item from vault to Character B

I'd have completely been lost on what the problem was. Would it be possible to create some error detection to determine that the vault is > 35 weapon items and pop an error that actually indicates what the user needs to do to resolve?

This really goes back to the original request on this issue. Moving items between characters and the vault is hard.  I get that. Note that the post that opened this issue is nearly opposite of this new observed behavior.
![91-1](https://cloud.githubusercontent.com/assets/2037051/7573750/9f343774-f7ed-11e4-8dce-8d43bd7ed92c.png)
![91-2](https://cloud.githubusercontent.com/assets/2037051/7573753/a5e56c50-f7ed-11e4-9692-9337c9de447f.png)
![91-3](https://cloud.githubusercontent.com/assets/2037051/7573756/af2e7d9c-f7ed-11e4-8121-a78bc6a7369c.png)

**Comment by dasilva333** [comment]
@rkingsla there's been a ton of fixes to address that specific issue of 'no items slots available' after using the loadouts, try getting it to break or crash and feel free to close out the ticket once you verified 2.5.4 is working right. thanks man

**Comment by rkingsla** [comment]
Hey Richard!  I’m out of town working with a customer, and haven’t had a chance to test or even use TGD since Sunday. I’ll be exercising it heavily over the weekend.  Crota and the Vault of Glass are calling me…

 

I *LOVE* what I see.  It is really maturing.  Nice work, team!

**Comment by dasilva333** [comment]
Hey guys I'm closing this old issue in favor of issue #236 and #240, it will be fixed in the future feel free to leave any feedback there instead thanks
