### ISSUE TITLE
Failure to log in on Firefox - Redirects to Bungie.net homepage

### ISSUE THREAD

**Issue by codeman6100** [dasilva333/TowerGhostForDestiny#92]
As soon as the login window closes, the extension page redirects to bungie.net.  I have not found a way to actually load my info in Tower Ghost.

**Comment by dasilva333** [comment]
After you get redirected to the bungie page try clicking on the icon again and it should be fine, if it continues to say you're not logged in try staying in the bungie page for a little bit longer because something has to get enabled for my extension to work. @codeman6100 report back thanks

**Comment by codeman6100** [comment]
Well I let it sit for a minute or two and it sill keeps looping me with:

Click on Extension Icon
-Error: Please Sign-In -> Live Sign-in
Login Page pops up and closes
Then bungie.net loads in the extension window.
Sit and Wait
^back to top ^

I just end up with lots of tabs open to bungie.net

**Comment by dasilva333** [comment]
Try this:

Click on Extension Icon
-Error: Please Sign-In -> Live Sign-in
Login Page pops up and closes
Then bungie.net loads in the extension window.
Click around like visit the homepage, visit another page, let things happen (I don't know why this is necessary) but I'm using 2.0.9 on Firefox 37 Windows and I had to make sure I was fully logged in
^back to top ^ (at this point the items should be loaded with no error)

**Comment by codeman6100** [comment]
I tried, went to like every bungie page, even went to outlook.com to check live login.  Still same issue.  I also tried login out and back in on live.

**Comment by dasilva333** [comment]
Try 2.0.9 if you're on 2.1.0 or 2.1.1 I can confirm that works, also provide your version number

**Comment by codeman6100** [comment]
I was on 2.1.0, then updated to 2.1.1.  Still with same issues.  As for 2.0.9, the xpi is not on AMO?

**Comment by dasilva333** [comment]
@codeman6100 Try 2.1.8 in the store and let me know if you still have problems, if you do please try 1.9.8 and see if that works for you.
https://github.com/dasilva333/TowerGhostForDestiny/commit/7eba515f0349592934ef8de8b99065125f41adb8

**Comment by codeman6100** [comment]
I tried both 2.1.7, .8 is not on firefox addons yet, and 1.9.8 and neither
works.  Is bungie.net supposed to load in the live login window or in the
TG tab?  Right now it is loading in the TG tab and the live login window is
up for less than a second since I am already logged in.

**Comment by dasilva333** [comment]
@codeman6100 thanks man you're feedback inspired me to find a fix for that. See in Chrome it behaves find the popup opens, you log in, you close the popup and the extension loads. In Firefox for some reason the extension gets redirected, anyhow I fixed it so it doesn't redirect the extension so the process would be:

1. click sign in
2. new tab opens you sign in, page redirects to bungie
3. close the new tab
4a. go back to the new tab and hit refresh 
4b. open the app again and close the old tab

Expect the fix in 2.1.9 Thanks

**Comment by codeman6100** [comment]
Awesome!  Cannot wait to try it.

**Comment by dasilva333** [comment]
@codeman6100 2.1.9 was released you can find it here:
https://addons.mozilla.org/en-us/firefox/addon/tower-ghost-for-destiny/

this is going to be placeholder version before I implement the next change which will make it behave more like Chrome where it opens a new window not a tab and it auto loads on close. I just need to make sure that these changes fixed it for you before I add the extra stuff on top. Let me know thanks

**Comment by codeman6100** [comment]
Well, I hate to be the barer of bad news but still no luck.  I end up at
the TG tab with the sign-in again.

**Comment by dasilva333** [comment]
@codeman6100 what version of Firefox are you using? Can you try updating to the latest version? I'm wondering whether this is an isolated case or if it's specific to a version of Firefox. Let me know thanks

**Comment by codeman6100** [comment]
I tried the previous versions on the latest Firefox version 37.0.2 and the
current developer build 39.0a2. I have only tested  TG 2.1.9 on the
developer build so far.

**Comment by dasilva333** [comment]
Not sure I'll be making a debug build for you to test out and see if we can figure out the problem. Thanks

**Comment by codeman6100** [comment]
So I have tried the new 2.2.* builds on both versions to no success.  Not
sure what is causing the problem on my end.

**Comment by codeman6100** [comment]
Still no luck with the latest build (2.6.3) on Firefox 38.0.1

**Comment by jaryanp** [comment]
I am also unable to connect on Firefox 38.0.1 
After logging out of bungie.net and clicking the PSN icon, it opens the window to sign into my PSN account, then closes and opens my bungie.net profile. I then clicked the Refresh (secs) button for TGD and it gives me the green bar saying "Please wait, loading arsenal from Bungie."

**Comment by dasilva333** [comment]
Try the instructions I provided earlier instead of using the refresh button:

click sign in
new tab opens you sign in, page redirects to bungie
close the new tab 
4a. go back to the new tab and hit refresh (doesnt work)
4b. open the app again and close the old tab (works every time)

**Comment by jaryanp** [comment]
That worked! Must have missed that suggestion...I tried the 'navigate
around the bungie site' trick.

Thanks!

Ryan

On Fri, May 29, 2015, 10:39 AM Richard Pinedo <notifications@github.com>
wrote:

> Try the instructions I provided earlier instead of using the refresh
> button:
>
> click sign in
> new tab opens you sign in, page redirects to bungie
> close the new tab
> 4a. go back to the new tab and hit refresh (doesnt work)
> 4b. open the app again and close the old tab (works every time)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dasilva333/TowerGhostForDestiny/issues/92#issuecomment-106830323>
> .
>
-- 

Ryan Porter

**Comment by dasilva333** [comment]
This has been completely fixed and should automatically sign you in every time after you log in to Bungie.net without requiring any additional interaction. Try it out and let me know if you still have any issues.
